/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant/index'
import { Route as TrTokenRouteImport } from './routes/tr/$token'
import { Route as TrTokenIndexRouteImport } from './routes/tr/$token.index'
import { Route as TenantTenantKeyIndexRouteImport } from './routes/tenant/$tenantKey/index'
import { Route as TrTokenCodeRouteImport } from './routes/tr/$token.$code'
import { Route as TenantTenantKeyRoomsRouteImport } from './routes/tenant/$tenantKey/rooms'
import { Route as ApiPublicWebhooksDispatchRouteImport } from './routes/api/public/webhooks-dispatch'
import { Route as TenantTenantKeyRoomRoomIdRouteImport } from './routes/tenant/$tenantKey/room/$roomId'
import { Route as ApiPublicLogoTenantKeyRouteImport } from './routes/api/public/logo.$tenantKey'
import { Route as ApiPublicStreamTenantKeyRoomIdRouteImport } from './routes/api/public/stream.$tenantKey.$roomId'
import { Route as ApiPublicSnapshotTenantKeyRoomIdRouteImport } from './routes/api/public/snapshot.$tenantKey.$roomId'
import { Route as ApiPublicEntryBgTenantKeyEntryIdRouteImport } from './routes/api/public/entry-bg.$tenantKey.$entryId'
import { Route as ApiPublicAdTenantKeyAdIdRouteImport } from './routes/api/public/ad.$tenantKey.$adId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrTokenRoute = TrTokenRouteImport.update({
  id: '/tr/$token',
  path: '/tr/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TrTokenIndexRoute = TrTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrTokenRoute,
} as any)
const TenantTenantKeyIndexRoute = TenantTenantKeyIndexRouteImport.update({
  id: '/tenant/$tenantKey/',
  path: '/tenant/$tenantKey/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrTokenCodeRoute = TrTokenCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => TrTokenRoute,
} as any)
const TenantTenantKeyRoomsRoute = TenantTenantKeyRoomsRouteImport.update({
  id: '/tenant/$tenantKey/rooms',
  path: '/tenant/$tenantKey/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksDispatchRoute =
  ApiPublicWebhooksDispatchRouteImport.update({
    id: '/api/public/webhooks-dispatch',
    path: '/api/public/webhooks-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantTenantKeyRoomRoomIdRoute =
  TenantTenantKeyRoomRoomIdRouteImport.update({
    id: '/tenant/$tenantKey/room/$roomId',
    path: '/tenant/$tenantKey/room/$roomId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLogoTenantKeyRoute = ApiPublicLogoTenantKeyRouteImport.update({
  id: '/api/public/logo/$tenantKey',
  path: '/api/public/logo/$tenantKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamTenantKeyRoomIdRoute =
  ApiPublicStreamTenantKeyRoomIdRouteImport.update({
    id: '/api/public/stream/$tenantKey/$roomId',
    path: '/api/public/stream/$tenantKey/$roomId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSnapshotTenantKeyRoomIdRoute =
  ApiPublicSnapshotTenantKeyRoomIdRouteImport.update({
    id: '/api/public/snapshot/$tenantKey/$roomId',
    path: '/api/public/snapshot/$tenantKey/$roomId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEntryBgTenantKeyEntryIdRoute =
  ApiPublicEntryBgTenantKeyEntryIdRouteImport.update({
    id: '/api/public/entry-bg/$tenantKey/$entryId',
    path: '/api/public/entry-bg/$tenantKey/$entryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdTenantKeyAdIdRoute =
  ApiPublicAdTenantKeyAdIdRouteImport.update({
    id: '/api/public/ad/$tenantKey/$adId',
    path: '/api/public/ad/$tenantKey/$adId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tr/$token': typeof TrTokenRouteWithChildren
  '/tenant/': typeof TenantIndexRoute
  '/api/public/webhooks-dispatch': typeof ApiPublicWebhooksDispatchRoute
  '/tenant/$tenantKey/rooms': typeof TenantTenantKeyRoomsRoute
  '/tr/$token/$code': typeof TrTokenCodeRoute
  '/tenant/$tenantKey/': typeof TenantTenantKeyIndexRoute
  '/tr/$token/': typeof TrTokenIndexRoute
  '/api/public/logo/$tenantKey': typeof ApiPublicLogoTenantKeyRoute
  '/tenant/$tenantKey/room/$roomId': typeof TenantTenantKeyRoomRoomIdRoute
  '/api/public/ad/$tenantKey/$adId': typeof ApiPublicAdTenantKeyAdIdRoute
  '/api/public/entry-bg/$tenantKey/$entryId': typeof ApiPublicEntryBgTenantKeyEntryIdRoute
  '/api/public/snapshot/$tenantKey/$roomId': typeof ApiPublicSnapshotTenantKeyRoomIdRoute
  '/api/public/stream/$tenantKey/$roomId': typeof ApiPublicStreamTenantKeyRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tenant': typeof TenantIndexRoute
  '/api/public/webhooks-dispatch': typeof ApiPublicWebhooksDispatchRoute
  '/tenant/$tenantKey/rooms': typeof TenantTenantKeyRoomsRoute
  '/tr/$token/$code': typeof TrTokenCodeRoute
  '/tenant/$tenantKey': typeof TenantTenantKeyIndexRoute
  '/tr/$token': typeof TrTokenIndexRoute
  '/api/public/logo/$tenantKey': typeof ApiPublicLogoTenantKeyRoute
  '/tenant/$tenantKey/room/$roomId': typeof TenantTenantKeyRoomRoomIdRoute
  '/api/public/ad/$tenantKey/$adId': typeof ApiPublicAdTenantKeyAdIdRoute
  '/api/public/entry-bg/$tenantKey/$entryId': typeof ApiPublicEntryBgTenantKeyEntryIdRoute
  '/api/public/snapshot/$tenantKey/$roomId': typeof ApiPublicSnapshotTenantKeyRoomIdRoute
  '/api/public/stream/$tenantKey/$roomId': typeof ApiPublicStreamTenantKeyRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tr/$token': typeof TrTokenRouteWithChildren
  '/tenant/': typeof TenantIndexRoute
  '/api/public/webhooks-dispatch': typeof ApiPublicWebhooksDispatchRoute
  '/tenant/$tenantKey/rooms': typeof TenantTenantKeyRoomsRoute
  '/tr/$token/$code': typeof TrTokenCodeRoute
  '/tenant/$tenantKey/': typeof TenantTenantKeyIndexRoute
  '/tr/$token/': typeof TrTokenIndexRoute
  '/api/public/logo/$tenantKey': typeof ApiPublicLogoTenantKeyRoute
  '/tenant/$tenantKey/room/$roomId': typeof TenantTenantKeyRoomRoomIdRoute
  '/api/public/ad/$tenantKey/$adId': typeof ApiPublicAdTenantKeyAdIdRoute
  '/api/public/entry-bg/$tenantKey/$entryId': typeof ApiPublicEntryBgTenantKeyEntryIdRoute
  '/api/public/snapshot/$tenantKey/$roomId': typeof ApiPublicSnapshotTenantKeyRoomIdRoute
  '/api/public/stream/$tenantKey/$roomId': typeof ApiPublicStreamTenantKeyRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tr/$token'
    | '/tenant/'
    | '/api/public/webhooks-dispatch'
    | '/tenant/$tenantKey/rooms'
    | '/tr/$token/$code'
    | '/tenant/$tenantKey/'
    | '/tr/$token/'
    | '/api/public/logo/$tenantKey'
    | '/tenant/$tenantKey/room/$roomId'
    | '/api/public/ad/$tenantKey/$adId'
    | '/api/public/entry-bg/$tenantKey/$entryId'
    | '/api/public/snapshot/$tenantKey/$roomId'
    | '/api/public/stream/$tenantKey/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tenant'
    | '/api/public/webhooks-dispatch'
    | '/tenant/$tenantKey/rooms'
    | '/tr/$token/$code'
    | '/tenant/$tenantKey'
    | '/tr/$token'
    | '/api/public/logo/$tenantKey'
    | '/tenant/$tenantKey/room/$roomId'
    | '/api/public/ad/$tenantKey/$adId'
    | '/api/public/entry-bg/$tenantKey/$entryId'
    | '/api/public/snapshot/$tenantKey/$roomId'
    | '/api/public/stream/$tenantKey/$roomId'
  id:
    | '__root__'
    | '/'
    | '/tr/$token'
    | '/tenant/'
    | '/api/public/webhooks-dispatch'
    | '/tenant/$tenantKey/rooms'
    | '/tr/$token/$code'
    | '/tenant/$tenantKey/'
    | '/tr/$token/'
    | '/api/public/logo/$tenantKey'
    | '/tenant/$tenantKey/room/$roomId'
    | '/api/public/ad/$tenantKey/$adId'
    | '/api/public/entry-bg/$tenantKey/$entryId'
    | '/api/public/snapshot/$tenantKey/$roomId'
    | '/api/public/stream/$tenantKey/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrTokenRoute: typeof TrTokenRouteWithChildren
  TenantIndexRoute: typeof TenantIndexRoute
  ApiPublicWebhooksDispatchRoute: typeof ApiPublicWebhooksDispatchRoute
  TenantTenantKeyRoomsRoute: typeof TenantTenantKeyRoomsRoute
  TenantTenantKeyIndexRoute: typeof TenantTenantKeyIndexRoute
  ApiPublicLogoTenantKeyRoute: typeof ApiPublicLogoTenantKeyRoute
  TenantTenantKeyRoomRoomIdRoute: typeof TenantTenantKeyRoomRoomIdRoute
  ApiPublicAdTenantKeyAdIdRoute: typeof ApiPublicAdTenantKeyAdIdRoute
  ApiPublicEntryBgTenantKeyEntryIdRoute: typeof ApiPublicEntryBgTenantKeyEntryIdRoute
  ApiPublicSnapshotTenantKeyRoomIdRoute: typeof ApiPublicSnapshotTenantKeyRoomIdRoute
  ApiPublicStreamTenantKeyRoomIdRoute: typeof ApiPublicStreamTenantKeyRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/$token': {
      id: '/tr/$token'
      path: '/tr/$token'
      fullPath: '/tr/$token'
      preLoaderRoute: typeof TrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/$token/': {
      id: '/tr/$token/'
      path: '/'
      fullPath: '/tr/$token/'
      preLoaderRoute: typeof TrTokenIndexRouteImport
      parentRoute: typeof TrTokenRoute
    }
    '/tenant/$tenantKey/': {
      id: '/tenant/$tenantKey/'
      path: '/tenant/$tenantKey'
      fullPath: '/tenant/$tenantKey/'
      preLoaderRoute: typeof TenantTenantKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/$token/$code': {
      id: '/tr/$token/$code'
      path: '/$code'
      fullPath: '/tr/$token/$code'
      preLoaderRoute: typeof TrTokenCodeRouteImport
      parentRoute: typeof TrTokenRoute
    }
    '/tenant/$tenantKey/rooms': {
      id: '/tenant/$tenantKey/rooms'
      path: '/tenant/$tenantKey/rooms'
      fullPath: '/tenant/$tenantKey/rooms'
      preLoaderRoute: typeof TenantTenantKeyRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks-dispatch': {
      id: '/api/public/webhooks-dispatch'
      path: '/api/public/webhooks-dispatch'
      fullPath: '/api/public/webhooks-dispatch'
      preLoaderRoute: typeof ApiPublicWebhooksDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/$tenantKey/room/$roomId': {
      id: '/tenant/$tenantKey/room/$roomId'
      path: '/tenant/$tenantKey/room/$roomId'
      fullPath: '/tenant/$tenantKey/room/$roomId'
      preLoaderRoute: typeof TenantTenantKeyRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/logo/$tenantKey': {
      id: '/api/public/logo/$tenantKey'
      path: '/api/public/logo/$tenantKey'
      fullPath: '/api/public/logo/$tenantKey'
      preLoaderRoute: typeof ApiPublicLogoTenantKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream/$tenantKey/$roomId': {
      id: '/api/public/stream/$tenantKey/$roomId'
      path: '/api/public/stream/$tenantKey/$roomId'
      fullPath: '/api/public/stream/$tenantKey/$roomId'
      preLoaderRoute: typeof ApiPublicStreamTenantKeyRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/snapshot/$tenantKey/$roomId': {
      id: '/api/public/snapshot/$tenantKey/$roomId'
      path: '/api/public/snapshot/$tenantKey/$roomId'
      fullPath: '/api/public/snapshot/$tenantKey/$roomId'
      preLoaderRoute: typeof ApiPublicSnapshotTenantKeyRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/entry-bg/$tenantKey/$entryId': {
      id: '/api/public/entry-bg/$tenantKey/$entryId'
      path: '/api/public/entry-bg/$tenantKey/$entryId'
      fullPath: '/api/public/entry-bg/$tenantKey/$entryId'
      preLoaderRoute: typeof ApiPublicEntryBgTenantKeyEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ad/$tenantKey/$adId': {
      id: '/api/public/ad/$tenantKey/$adId'
      path: '/api/public/ad/$tenantKey/$adId'
      fullPath: '/api/public/ad/$tenantKey/$adId'
      preLoaderRoute: typeof ApiPublicAdTenantKeyAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrTokenRouteChildren {
  TrTokenCodeRoute: typeof TrTokenCodeRoute
  TrTokenIndexRoute: typeof TrTokenIndexRoute
}

const TrTokenRouteChildren: TrTokenRouteChildren = {
  TrTokenCodeRoute: TrTokenCodeRoute,
  TrTokenIndexRoute: TrTokenIndexRoute,
}

const TrTokenRouteWithChildren =
  TrTokenRoute._addFileChildren(TrTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrTokenRoute: TrTokenRouteWithChildren,
  TenantIndexRoute: TenantIndexRoute,
  ApiPublicWebhooksDispatchRoute: ApiPublicWebhooksDispatchRoute,
  TenantTenantKeyRoomsRoute: TenantTenantKeyRoomsRoute,
  TenantTenantKeyIndexRoute: TenantTenantKeyIndexRoute,
  ApiPublicLogoTenantKeyRoute: ApiPublicLogoTenantKeyRoute,
  TenantTenantKeyRoomRoomIdRoute: TenantTenantKeyRoomRoomIdRoute,
  ApiPublicAdTenantKeyAdIdRoute: ApiPublicAdTenantKeyAdIdRoute,
  ApiPublicEntryBgTenantKeyEntryIdRoute: ApiPublicEntryBgTenantKeyEntryIdRoute,
  ApiPublicSnapshotTenantKeyRoomIdRoute: ApiPublicSnapshotTenantKeyRoomIdRoute,
  ApiPublicStreamTenantKeyRoomIdRoute: ApiPublicStreamTenantKeyRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
